FROM nvidia/cuda:11.3.0-cudnn8-runtime-ubuntu20.04

WORKDIR /research

RUN apt-get update

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    build-essential \
    git \
    python3 \
    python3-pip \
    python

ENV HOME /research
ENV PYENV_ROOT $HOME/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

RUN apt-get install -y python-setuptools

RUN update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1 && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3.8 2

RUN apt-get install -y virtualenv htop
RUN pip install --upgrade numpy scipy sklearn tf-nightly-gpu
#RUN pip install --upgrade numpy scipy sklearn tensorflow-gpu==2.2.0

# Mount data into the docker
ADD . /research/resnet
ADD ./tf2 /research/resnet-tf2

WORKDIR /research/resnet
RUN pip install -r official/requirements.txt

ENTRYPOINT ["/bin/bash"]
